server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beavildatas
    username: root
    password: 27963608
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
